<a href="https://colab.research.google.com/github/Sameeulla-A/PyTorch/blob/main/Python/10_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Python is designed to be light weight and easy to use, so there are tons of tons functions uncountable number of functions availble in python do not come directly accessible with the basic installation of python.
* that make sense, every possible function had to be bundled into python program, it would be huge, sluggish to start the python.
* instead of that the base installation of the python is very simple and straight forward and very light weight. it doesn't come with lot of built-in functions.
* some functions are availble in libraries.
* libraries are the collection of the functions, and classes and other kind of variable types.

* import is reserve keyword.
* numpy --> is a package written for python numpy , numerical python.
* we are importing numpy with abbreviation np. so we can access all the function in numpy.
* np.function()

let's try without numpy.

In [1]:
import numpy as np
num = [10,12,25.5]
mean(num)

NameError: name 'mean' is not defined

In [14]:
#lets try numpy function
import numpy as np
numbers = [10,12,25]
np.mean(numbers) # mean is not a built-in function in python

np.float64(15.666666666666666)

* numpy.linspace() function returns evenly spaced numbers over a specified mathematical interval.
* Return evenly spaced numbers over a specified interval.
* Returns num evenly spaced samples, calculated over the interval [start, stop].
* The endpoint of the interval can optionally be excluded.
* np.linspace(1,7,5)
* and the output is neither list nor tuple, its a numpy array.

In [15]:
np.linspace(1,7,5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [16]:
x = np.linspace(1,7,5)
type(x)

numpy.ndarray

* An ndarray (N-dimensional array) is the core data structure of the NumPy library in Python. It is a fast, flexible, and multidimensional container designed to hold homogeneous data.

In [17]:
# convert the list into ndarray
np_nums = np.array(numbers)
print(type(numbers))
print(np_nums)
print(type(np_nums))

<class 'list'>
[10 12 25]
<class 'numpy.ndarray'>


In [18]:
print(np_nums.mean())
print(np_nums.max())
print(np_nums.min())

# or

print(np.mean(np_nums))
print(np.max(np_nums))
print(np.min(np_nums))

15.666666666666666
25
10
15.666666666666666
25
10


In [19]:
np.mean(numbers)  # it will work directly on list

np.float64(15.666666666666666)

* we can import the functions which required using from

In [23]:
from numpy import mean as m  #we are not importing entire library

In [25]:
mean(num)

np.float64(15.833333333333334)

In [26]:
m(num)

np.float64(15.833333333333334)

In [27]:
# In-Place Operations
# Out-of-Place Operations / not in-place operations
n = [ 4,3,5,2,6,1,7 ]  # unsorted list
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


* when we apply sort on a list, then it's going to actually change the variable, doesn't just print out the sorted version or return a sorted version as different variable.
* it actually fundamentally changes the variable.
* similar process works with methods in numpy

In [29]:
m = [ 9,5,8,6,7,2,4,3,1 ]
nn = np.array(m) # does the same thing happens with numpy array as above.
print(nn)
nn.sort()
print(nn)

[9 5 8 6 7 2 4 3 1]
[1 2 3 4 5 6 7 8 9]


In [31]:
# now let's call the numpy function
p = [ 9,5,8,6,7,2,4,3,1 ]
no = np.array(p) # does the same thing happens with numpy array as above.
print(p)
np.sort(no)
print(no)

[9, 5, 8, 6, 7, 2, 4, 3, 1]
[9 5 8 6 7 2 4 3 1]


* it doesn't actually change ,  beacause it's an inplace operation

In [32]:
# let's try out place operation
p = [ 9,5,8,6,7,2,4,3,1 ]
no = np.array(p) # does the same thing happens with numpy array as above.
print(p)
op = np.sort(no)
print(op)

[9, 5, 8, 6, 7, 2, 4, 3, 1]
[1 2 3 4 5 6 7 8 9]


* **Note:**  certain operations in python operate in-place, meaning variable is changing. and certain operation are not in-pace meaning that they don't change the variable on it's own or you can overwrite the existing variable.